language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make build
branches:
  only:
  - master
env:
  global:
  - secure: fxnec2rNsUVBkm4afwtgyhJgoDQtv2F1bc5nVIcpBbyO59haKHR7TPT5q+5CA9JbjhhpT/Ze+rPzV5UlpvR+opxToqNAfTomFh+k4udQf7Li3xsEjugTEO1Ku82Nq5aUT3HBtsDEflbMmq8KuOuGIDJ3BE6fodnWai0teaC1CnPyNVdGivxn+gOZqFamk0G6vfaZDi6pccN+tmMAJZCcls/hGkxykYTTFzYSNjLvlTLBCVSJSSqNAg7heAf9J/m9QYr3FHuHPZIw9HtVzXjfD3NI8OoWFLQQDX+biZciXBQMXUdoewT7pmD1Dp7q8ongsBrT9ugygw7t17X1YYS+i0mbuGBT4tPWmVYYrUe33e2D99a3K1MKJ7YYmQ1oC4ScyJb9SCLu3t+zt6tLqCWjyqki5kzEqN6VRX/WhEq9mbiWvSUK05WYywl/kT9Ju8o804PrDzfAhBzu/RNFoCGGNw1+FGwYWZb73sRopMgAyuFPnMLU/w5o1r6IJJhNsJlZkWT3fF3exoKxfyX0uBH3HIDlUnEkOx5MAS+24D5YtWzXyH/CXxrOJnt1sUcZrUlJccBxosFUJvi71VQsfPOsj3J+A6r4/8rLCpUY3vA4xmULaoefVI39mdEqedoHPy5lLshRRC9Qh6aNeHbPDvRmzdMbAKYYflb2syhij7OlptY=
  - secure: Tlf2R6L5tiAnhgWB9ogD7+a7bbUBoagpMMJjQTN1flfXcnfR4gf2f2OPRIy7FkcE30tin5xLES2VJ0XBNMFHXT38p0wnAW/IcXsKsDhI4ytEI9lnLqOjq2wv7/PkB2VcWJmxnUU/T7oPRyZNWnhYhpMC3AA5Dquos1I7BjohzWo1UVnVeGPeQ/bK7dX044bCyNPKJUVN6aRQN0bZ5xssoDt64KrLuaQ4B5qU1TjkoytvjdhWDtsqyWTK+wQzNujDLueN7fWcpdV2NAo2KuUAlIobnoXI8jiNC5JmEneQnZYtRyO7ptagi4w2OSBb6at318Vb8ScvCd8GZ0PdJCNrOtaeXxe34TUGVieO33djNHxMzajGChHz0G49P2xSixACT5FJdzSPjjtHQ6kBv+m8bNo9dVW6S6jvsUIf6DpZ2K7dkciLYqOIxqOYDx9Z4hNy6e5VGN1WW7a9fOsmosH0sHqaezj65JvFWbB1D72h86BANY7KCgoTBMzc3drRXij2ozWZ1FXxXF+mnimOqgN95XweQ7RABcwUCs6SrR+zdiaV4np1Io1OzdXRnMxAAlO/Yf2pZ/5gDZjqDfG5dObxdzuQHfQvjgKK3aCQDTcGgUAdmj5g3OIhOwKWjZEE+04GeYSUF72OKb9VRn+gMf6gL6puFmkLS1aheJhH9vzpvuQ=
